### ISSUE TITLE
Error while creating a new Control Plugin for Xamarin.Forms

### ISSUE THREAD

**Issue by psharrma** [jamesmontemagno/Xamarin-Templates#11] opened 2016-11-27 04:07 UTC
Upon trying to create a new Control plugin i get below errors dialogs and UWP project is not created:

---------------------------
Microsoft Visual Studio
---------------------------
Package Installation Error

Could not add all required packages to the project. The following packages failed to install from 'C:\USERS\PSHAR\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\E2HCD152.5QO\Packages':

WPtoolkit.4.2013.8.16 : Unable to find version '4.2013.8.16' of package 'WPtoolkit'.
---------------------------
OK   
---------------------------

---------------------------
Microsoft Visual Studio
---------------------------
A problem was encountered creating the sub project 'VLC.FormsPlugin.UWP'.  Unable to copy the file 'VLC.FormsPlugin.UWP.rd.xml' from the project template to the project. Cannot find file "E:\Temp\stz3fqpi.igk\Temp\Properties\VLC.FormsPlugin.UWP.rd.xml".
---------------------------
OK   
---------------------------

**Comment by jamesmontemagno** [comment] 2016-11-27 20:06
Duplicate of #6

**Closed as completed by jamesmontemagno** 2016-11-27 20:06 UTC

**Comment by psharrma** [comment] 2016-11-29 07:11
Thanks for directing me towards original issue, and will keep in mind next time onwards to check for any pre-logged issues.

I tried the fix suggested in the original issue(i.e. placing the WPtoolkit package at expected location), This fixed first issue but still project is not created and I could see the second dialog.
